### ISSUE TITLE
Attempt to index local 'test_results' (a nil value)

### ISSUE THREAD

**Issue by MrFisher404** [Issafalcon/neotest-dotnet#7]
Hi thanks first of all for your fast response from my last issue.

Now the tests are running. But after I get a notification "Neotest: Success" I get the following message.

neotest-dotnet/lua/neotest-dotnet/init.lua:132: attempt to index local 'test_results' (a nil value)

I looked one time in this xml and json which is generated there and I couldn't find any tes_result. Not sure if this is a misconfiguration of mine or not.
I realized that it only happens when I run a single test. I guess it is related to my other issue, that if I run a single test the "green tick" won't appear (not in the summary nor in the file) but if I run the whole class or file, everything works fine.

Thank you for your time and effort. It is really appreciated. 
Next I want to try the debugger :)

**Comment by Issafalcon** [comment]
Hi @MrFisher404 . No problem. The less time I need to spend in Visual Studio, the better 😋 , so making the dotnet workflow in Neovim better is my mission at the moment. 

Thanks for raising the issue. I'll admit, I never actually tested with individual test runs using the neotest commands for all the frameworks, so I'll check this out when I next get chance.

**Comment by Issafalcon** [comment]
Hi @MrFisher404 - Please try and update neotest and neotest-dotnet plugins and see if this still occurs. I've noticed there is a new issue when there is a test marked as [Ignore] (or similar attributes depending on the test runner) where there is an erroneous signal sent to neotest and it doesn't appear to be able to run any more testts after that. However, other than that, I can't recreate what you mention above with the latest updates to the plugins.

If you still have the issue, please provide the following info:
- The test runner you're using (Nunit etc)
- The neotest config you have
- Logs from neotest (set the log_level in the neotest options to 1 for verbose logging)

**Comment by Issafalcon** [comment]
#11

**Comment by Issafalcon** [comment]
@MrFisher404 - I'm fairly sure this should be fixed now by the linked PR's. I could recreate the issue when I forced a runtime error (so the trx file is produced but there are no test results, hence test_results is nil). Making the assumption that if there are no test_results in the output, then there is some sort of runtime error, I've updated the code accordingly.

I've also fixed a couple of NUnit specific quirks as well.

I'll close this issue for now, but if you still fine problems, feel free to raise another issue.

**Comment by MrFisher404** [comment]
Hi! Thank you again for your fast reply and your fast fixes. I definitely saw an improvement. I can see now the summaries of the tests and can get the output as well.
But I still have an issue with running single tests. 
When I use "Run nearest" the output which I get is:

No test matches the given testcase filter 'FullyQualifiedName=NameOfTestClass.NameOfTest' in /absolute/path/to/Test.dll

I don't understand why it doesn't find it since the path to the dll is correct and the name of the test and the test class are also correct. Any Idea?

**Comment by Issafalcon** [comment]
Do you happen to have a sample test file you are running from, or an equivalent that I can use to try and reproduce from? Also, which test runner are you using? Is it NUnit?

My first thought, based on your comment, is that the namespace is missing on the fully qualified name filter. Are you using the new namespace syntax where you don't enclose the namespace in curly braces? i.e:

```
namespace SomeNamespace;

public class ClassIsScopedInANamespace {
    // ... Some class implementation.
}
```

In which case, it might be treesitter isn't picking up the namespace, and isn't passing it to the filter.

**Comment by Issafalcon** [comment]
@MrFisher404 - I've confirmed that various formations of `using` and `namespace` syntax are not all accounted for, so this could explain it. See #14

**Comment by MrFisher404** [comment]
Hey sorry for the late reply. Yes we use file-Scoped namespaces. I will keep an eye on that bug.
Thank you for keeping up the good work!
